
version: "3"
networks:
  local:
    external: true
services:
  web:
    image: nginx:latest
    networks:
      - local
    ports:
      - 8080:80
      - 80:80
      - 443:443
    expose:
      - "80"
      - "443"
    volumes:
      - ./../:/var/www/html
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
  php:
    image: php_composer
    networks:
      - local
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    environment:
      COMPOSER_HOME: /var/www/html/.composer
    volumes:
      - ./../:/var/www/html
    tty: true
    networks:
      - default
networks:
  default:
    driver: bridge